#!/bin/bash

if [[ ! -f build/smart_wrapper.profdata || build/smart_wrapper -nt build/smart_wrapper.profraw ]]; then
    LLVM_PROFILE_FILE='build/smart_wrapper.profraw' build/smart_wrapper
    llvm-profdata merge build/smart_wrapper.profraw -o build/smart_wrapper.profdata
    rm build/smart_wrapper.profraw
fi

llvm-cov show -format html -instr-profile build/smart_wrapper.profdata build/smart_wrapper > smart_wrapper_coverage.html
llvm-cov report -instr-profile build/smart_wrapper.profdata build/smart_wrapper > smart_wrapper.report
llvm-cov export -instr-profile build/smart_wrapper.profdata build/smart_wrapper > smart_wrapper_coverage.json
